apiVersion: v1
kind: Namespace
metadata:
  name: oms-app
---
# ==========================
# MySQL Database
# ==========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: oms-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: oms-app
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: oms-app
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
# ================================
# RabbitMQ
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: oms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672   # RabbitMQ
        - containerPort: 15672  # Management UI
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: oms-app
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: NodePort
# ================================
# User Service
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: oms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: swathich1/user-service:latest   # your DockerHub image
        ports:
        - containerPort: 8082      
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/oms_user
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: mysql  
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: oms-app
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082
  type: NodePort
---
# ================================
# Order Service
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: oms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: swathich1/order-service:latest   # your DockerHub image
        ports:
        - containerPort: 8081       
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/oms_order
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: oms-app
spec:
  selector:
    app: order-service
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort
---
# ================================
# Notification Service
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: oms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: swathich1/notification-service:latest   # your DockerHub image
        ports:
        - containerPort: 8083       
        env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/oms_notification
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: mysql  
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: oms-app
spec:
  selector:
    app: notification-service
  ports:
    - port: 8083
      targetPort: 8083
  type: NodePort